### ISSUE TITLE
Device Type Init check

### ISSUE THREAD

**Issue by vChavezB** [pilotak/BQ35100#4]
Thanks for the driver. I am porting to another platform and when I was reading the code I found out a possible mistake.

You are reading the HW Version 

https://github.com/pilotak/BQ35100/blob/8de11eba1f43c0da0b9a5933caaa220adb2b7aad/BQ35100.cpp#L61-L64

however in the comments you mention that you are trying to obtain the device type (i.e. 0x100 according to Table 11-2. Control MAC Subcommands).

**Comment by pilotak** [comment]
Well spotted, this HW_VERSION can differ against different manufacturing years. It worked when i first wrote it because i had same batch.  It should read `CNTL_DEVICE_TYPE` and on line 70 there should be `0x40` https://github.com/pilotak/BQ35100/blob/8de11eba1f43c0da0b9a5933caaa220adb2b7aad/BQ35100.cpp#L70

do you want to submit a PR and test it? as i have not got the device with me anymore, it's in the field

**Comment by vChavezB** [comment]
Sure, I will have a look on it once I have the hardware with me.

**Comment by vChavezB** [comment]
I still have to check with the driver what values I get but at least in the BQ Studio software from TI these are the values I got from my BQ35100 IC

![grafik](https://github.com/pilotak/BQ35100/assets/47216966/4f33fb2d-a363-4c19-81ee-47681b076dbb)

**Comment by vChavezB** [comment]
I can confirm you that the device number is 0x100. See datasheet Table 11-2. Control MAC Subcommands.

**Comment by pilotak** [comment]
this is strange - in datasheet https://www.ti.com/lit/ds/symlink/bq35100.pdf in Table 2 there is result of `0x40` and in technical note https://www.ti.com/lit/ug/sluubh1c/sluubh1c.pdf there is `0x0100` but they are talking about some block read?

**Comment by vChavezB** [comment]
Yes, seems that there is a mistake on the datasheet. In the technical reference manual the value is 0x100 instead of 0x40. 

![grafik](https://github.com/pilotak/BQ35100/assets/47216966/2aa4a002-14f2-4ad6-84fe-66c0f06dd2e8)


After testing I can confirm the value I get from DEVICE_TYPE is 0x100

**Comment by pilotak** [comment]
Thanks a lot
